import os
from dotenv import load_dotenv

load_dotenv()

# Short-term memory (Redis)
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DB = int(os.getenv("REDIS_DB", "0"))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD") or None
REDIS_MAX_MESSAGES = int(os.getenv("REDIS_MAX_MESSAGES", "50"))

# Long-term memory (Neo4j)
MEMORY_VECTOR_INDEX = os.getenv("MEMORY_VECTOR_INDEX", "memory_embedding")
MEMORY_RECALL_LIMIT = int(os.getenv("MEMORY_RECALL_LIMIT", "5"))
MEMORY_RECALL_RELATION_LIMIT = int(os.getenv("MEMORY_RECALL_RELATION_LIMIT", "5"))
MEMORY_RECALL_EXPANSION_LIMIT = int(os.getenv("MEMORY_RECALL_EXPANSION_LIMIT", "10"))
MEMORY_RECALL_MIN_SCORE = float(os.getenv("MEMORY_RECALL_MIN_SCORE", "0.0"))
MEMORY_DEFAULT_IMPORTANCE = float(os.getenv("MEMORY_DEFAULT_IMPORTANCE", "0.5"))
MEMORY_ENRICHMENT_ENABLED = os.getenv("MEMORY_ENRICHMENT_ENABLED", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
MEMORY_ENRICHMENT_CANDIDATE_LIMIT = int(os.getenv("MEMORY_ENRICHMENT_CANDIDATE_LIMIT", "5"))
MEMORY_ENRICHMENT_MAX_ATTEMPTS = int(os.getenv("MEMORY_ENRICHMENT_MAX_ATTEMPTS", "3"))
MEMORY_ENRICHMENT_RETRY_BACKOFF_SECONDS = float(os.getenv("MEMORY_ENRICHMENT_RETRY_BACKOFF_SECONDS", "5"))
MEMORY_ENRICHMENT_SIMILARITY_LIMIT = int(os.getenv("MEMORY_ENRICHMENT_SIMILARITY_LIMIT", "5"))
MEMORY_ENRICHMENT_SIMILARITY_THRESHOLD = float(os.getenv("MEMORY_ENRICHMENT_SIMILARITY_THRESHOLD", "0.8"))

# Consolidation (reuses v1 env key names)
MEMORY_CONSOLIDATION_ENABLED = os.getenv("MEMORY_CONSOLIDATION_ENABLED", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
CONSOLIDATION_TICK_SECONDS = int(os.getenv("CONSOLIDATION_TICK_SECONDS", "60"))
CONSOLIDATION_DECAY_INTERVAL_SECONDS = int(os.getenv("CONSOLIDATION_DECAY_INTERVAL_SECONDS", "86400"))
CONSOLIDATION_CREATIVE_INTERVAL_SECONDS = int(os.getenv("CONSOLIDATION_CREATIVE_INTERVAL_SECONDS", "604800"))
CONSOLIDATION_CLUSTER_INTERVAL_SECONDS = int(os.getenv("CONSOLIDATION_CLUSTER_INTERVAL_SECONDS", "2592000"))
CONSOLIDATION_FORGET_INTERVAL_SECONDS = int(os.getenv("CONSOLIDATION_FORGET_INTERVAL_SECONDS", "0"))
_CONSOLLATION_DECAY_RAW = os.getenv("CONSOLIDATION_DECAY_IMPORTANCE_THRESHOLD", "0.3").strip()
CONSOLIDATION_DECAY_IMPORTANCE_THRESHOLD = (
    float(_CONSOLLATION_DECAY_RAW) if _CONSOLLATION_DECAY_RAW else None
)
CONSOLIDATION_HISTORY_LIMIT = int(os.getenv("CONSOLIDATION_HISTORY_LIMIT", "20"))
CONSOLIDATION_BASE_DECAY_RATE = float(os.getenv("CONSOLIDATION_BASE_DECAY_RATE", "0.01"))
CONSOLIDATION_IMPORTANCE_FLOOR_FACTOR = float(os.getenv("CONSOLIDATION_IMPORTANCE_FLOOR_FACTOR", "0.3"))
CONSOLIDATION_DELETE_THRESHOLD = float(os.getenv("CONSOLIDATION_DELETE_THRESHOLD", "0.0"))
CONSOLIDATION_ARCHIVE_THRESHOLD = float(os.getenv("CONSOLIDATION_ARCHIVE_THRESHOLD", "0.0"))
CONSOLIDATION_GRACE_PERIOD_DAYS = int(os.getenv("CONSOLIDATION_GRACE_PERIOD_DAYS", "90"))
CONSOLIDATION_IMPORTANCE_PROTECTION_THRESHOLD = float(
    os.getenv("CONSOLIDATION_IMPORTANCE_PROTECTION_THRESHOLD", "0.7")
)
_PROTECTED_RAW = os.getenv("CONSOLIDATION_PROTECTED_TYPES", "Decision,Insight").strip()
CONSOLIDATION_PROTECTED_TYPES = frozenset(
    item.strip() for item in _PROTECTED_RAW.split(",") if item.strip()
) if _PROTECTED_RAW else frozenset()
CONSOLIDATION_CONTROL_LABEL = "ConsolidationControl"
CONSOLIDATION_RUN_LABEL = "ConsolidationRun"
CONSOLIDATION_CONTROL_NODE_ID = os.getenv("CONSOLIDATION_CONTROL_NODE_ID", "global")
CONSOLIDATION_TASK_FIELDS = {
    "decay": "decayLastRun",
    "creative": "creativeLastRun",
    "cluster": "clusterLastRun",
    "forget": "forgetLastRun",
    "full": "fullLastRun",
}
# Minimum sizes for creative/cluster grouping
CONSOLIDATION_CREATIVE_MIN_COUNT = int(os.getenv("CONSOLIDATION_CREATIVE_MIN_COUNT", "3"))
CONSOLIDATION_CLUSTER_MIN_NEIGHBORS = int(os.getenv("CONSOLIDATION_CLUSTER_MIN_NEIGHBORS", "3"))

MEMORY_SEARCH_WEIGHT_VECTOR = float(os.getenv("MEMORY_SEARCH_WEIGHT_VECTOR", "0.35"))
MEMORY_SEARCH_WEIGHT_KEYWORD = float(os.getenv("MEMORY_SEARCH_WEIGHT_KEYWORD", "0.35"))
MEMORY_SEARCH_WEIGHT_RELATION = float(os.getenv("MEMORY_SEARCH_WEIGHT_RELATION", "0.25"))
MEMORY_SEARCH_WEIGHT_TAG = float(os.getenv("MEMORY_SEARCH_WEIGHT_TAG", "0.2"))
MEMORY_SEARCH_WEIGHT_IMPORTANCE = float(os.getenv("MEMORY_SEARCH_WEIGHT_IMPORTANCE", "0.1"))
MEMORY_SEARCH_WEIGHT_CONFIDENCE = float(os.getenv("MEMORY_SEARCH_WEIGHT_CONFIDENCE", "0.05"))
MEMORY_SEARCH_WEIGHT_RECENCY = float(os.getenv("MEMORY_SEARCH_WEIGHT_RECENCY", "0.1"))
MEMORY_SEARCH_WEIGHT_EXACT = float(os.getenv("MEMORY_SEARCH_WEIGHT_EXACT", "0.2"))
